using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Business_Logic_Layer;
using EntitiesAndMapping.Entities;
using System.Data;

namespace TestWork_Nix.GoodsElements.Controls
{
    public partial class ListGoodsControl : System.Web.UI.UserControl
    {
        DataTable dataTable = new DataTable();
        public event EventHandler GoodsClick;
        public delegate void GoodsEventHandler();

        int selectedCategoryID = -1;
        bool isUser = false;

        protected void Page_Load(object sender, EventArgs e)
        {
            if (isUser)
            {
                GridViewGoods.AutoGenerateSelectButton = false;
                GridViewGoods.AutoGenerateDeleteButton = false;
            }

            if (!Page.IsPostBack && selectedCategoryID > 0)
            {
                GridViewBind();
            }
        }

        void GridViewBind()
        {
            GoodsActions goodsActions = new GoodsActions();
            List<Goods> listGoods = goodsActions.GetGoods(selectedCategoryID);

            if (listGoods.Count > 0)
            {
                dataTable.Columns.Add("ID");
                dataTable.Columns.Add("Image");
                dataTable.Columns.Add("Name");
                dataTable.Columns.Add("Price");
                dataTable.Columns.Add("IsDiscount");
                dataTable.Columns.Add("Discount");

                for (int i = 0; i < listGoods.Count; i++)
                {
                    dataTable.Rows.Add(listGoods[i].ID,
                        string.Format(@"ImageHelp.aspx?imgID={0}",
                        listGoods[i].ID),
                        listGoods[i].Name,
                        listGoods[i].Price + "грн",
                        listGoods[i].IsDiscount,
                        listGoods[i].Discount
                        );
                }
                ViewState.Add("dataTable", dataTable);

                GridViewGoods.DataSource = dataTable;
                GridViewGoods.DataBind();
            }
            else
            {
                Label1.Text = "This category don`t have a goods";
            }
        }

        //переделать под обработчик событий
        protected void GridViewGoods_SelectedIndexChanged(object sender, EventArgs e)
        {
            int index = GridViewGoods.SelectedRow.DataItemIndex;

            if (ViewState["dataTable"] != null)
            {
                dataTable = (DataTable)ViewState["dataTable"];
            }

            object[] row = dataTable.Rows[index].ItemArray;

            Session.Add("SelectedGoodsID", row[0]);

            Response.Redirect("~/Administrator/GoodsEdit.aspx");
        }

        protected void GridViewGoods_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int index = e.RowIndex;

            if (ViewState["dataTable"] != null)
            {
                dataTable = (DataTable)ViewState["dataTable"];

                object[] row = dataTable.Rows[index].ItemArray;

                int goodsID;
                int.TryParse(row[0].ToString(), out goodsID);

                if (goodsID != null)
                {
                    GoodsActions goodsActions = new GoodsActions();
                    goodsActions.DeleteGoods(goodsID);
                }
                dataTable.Rows.RemoveAt(index);
                GridViewGoods.DataSource = dataTable;
                ViewState.Add("dataTable", dataTable);
                GridViewGoods.DataBind();
            }
        }
    
        #region Properties

        public int SelectedCategoryID
        {
            get
            {
                return selectedCategoryID;
            }
            set
            {
                selectedCategoryID = value;
            }
        }

        public bool IsUser
        {
            get
            {
                return isUser;
            }
            set
            {
                isUser = value;
            }
        }

        #endregion

        public class GoodsEventArgs : EventArgs
        {
            public GoodsEventArgs()
            {

            }
        }
    }
}